# Generated by Django 3.0.6 on 2020-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_timeline_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_pics/')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(default='account_default.jpg', upload_to='member_pics/')),
                ('blood_group', models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, '0+'), (8, 'O-'), (9, 'OTHERS')], default=1, max_length=10)),
                ('sex', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1, max_length=10)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_1_india', models.IntegerField(null=True, verbose_name='Indian Phone (if exists)')),
                ('phone_2_gcc', models.IntegerField(null=True, verbose_name='GCC Phone (if exists)')),
                ('section', models.CharField(choices=[(1, 'INDIA'), (2, 'GCC')], default=1, max_length=5)),
                ('current_location', models.URLField(default='https://maps.app.goo.gl/aSoSHUyyFsuMZMsB6')),
                ('country', models.CharField(default='India', max_length=20)),
                ('city', models.CharField(default='Thrissur', max_length=20)),
                ('place', models.CharField(default='Aviyoor, Edakkara P.O', max_length=30)),
                ('occupation_or_course', models.CharField(default='Student', max_length=100, verbose_name='Occupation/Course')),
                ('company_or_institution_name', models.CharField(max_length=100, null=True, verbose_name='Company/Institution Name')),
                ('company_or_institution_place', models.CharField(max_length=100, null=True, verbose_name='Company/Institution Place')),
            ],
        ),
        migrations.AddField(
            model_name='timeline',
            name='image',
            field=models.ImageField(default='avasco_logo.jpeg', upload_to='timeline_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='avasco_logo.jpeg', upload_to='post_pics/'),
        ),
    ]
