# Generated by Django 3.0.6 on 2020-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200712_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='blood_group',
            field=models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, '0+'), (8, 'O-'), (9, 'OTHERS')], default=1, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='section',
            field=models.CharField(choices=[(1, 'INDIA'), (2, 'GCC')], default=1, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1, max_length=1, null=True),
        ),
    ]
