# Generated by Django 3.0.6 on 2020-07-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200712_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_member_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_1', to='blog.Member')),
                ('executive_member_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_2', to='blog.Member')),
                ('executive_member_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_3', to='blog.Member')),
                ('executive_member_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_4', to='blog.Member')),
                ('gcc_executive_member_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_1', to='blog.Member')),
                ('gcc_executive_member_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_2', to='blog.Member')),
                ('gcc_executive_member_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_3', to='blog.Member')),
                ('gcc_executive_member_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_4', to='blog.Member')),
                ('gcc_joint_secretary_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_joint_secretary_1', to='blog.Member')),
                ('gcc_joint_secretary_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_joint_secretary_2', to='blog.Member')),
                ('gcc_president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_president', to='blog.Member')),
                ('gcc_secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_secretary', to='blog.Member')),
                ('gcc_treasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_treasurer', to='blog.Member')),
                ('gcc_vice_president_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_vice_president_1', to='blog.Member')),
                ('gcc_vice_president_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_vice_president_2', to='blog.Member')),
                ('joint_secretary_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secretary_1', to='blog.Member')),
                ('joint_secretary_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secretary_2', to='blog.Member')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='blog.Member')),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='blog.Member')),
                ('treasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer', to='blog.Member')),
                ('vice_president_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_1', to='blog.Member')),
                ('vice_president_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_2', to='blog.Member')),
            ],
        ),
    ]
