# Generated by Django 3.0.6 on 2020-07-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='executive_member_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_1', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='executive_member_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_2', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='executive_member_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_3', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='executive_member_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_member_4', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_executive_member_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_1', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_executive_member_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_2', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_executive_member_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_3', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_executive_member_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_executive_member_4', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_joint_secretary_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_joint_secretary_1', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_joint_secretary_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_joint_secretary_2', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_president', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_secretary', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_treasurer', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_vice_president_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_vice_president_1', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='gcc_vice_president_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcc_vice_president_2', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='joint_secretary_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secretary_1', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='joint_secretary_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secretary_2', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='vice_president_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_1', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='vice_president_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_2', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='blood_group',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, '0+'), (8, 'O-'), (9, 'OTHERS')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
