# Generated by Django 3.0.6 on 2020-07-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200716_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='gcc_poster',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='india_poster',
        ),
    ]
