# Generated by Django 3.0.6 on 2020-07-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200716_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='gcc_poster',
            field=models.ImageField(blank=True, null=True, upload_to='committee_pics'),
        ),
        migrations.AddField(
            model_name='committee',
            name='india_poster',
            field=models.ImageField(blank=True, null=True, upload_to='committee_pics'),
        ),
    ]
