# Generated by Django 3.0.6 on 2020-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200719_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, default='avasco_logo.jpeg', null=True, upload_to='post_pics/'),
        ),
    ]
