# Generated by Django 3.0.6 on 2020-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200719_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
    ]
