# Generated by Django 3.0.6 on 2020-07-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200719_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avasco_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Avasco ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, default='avasco.jpeg', null=True, upload_to='post_pics/'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=models.ImageField(default='avasco.jpeg', upload_to='timeline_pics/'),
        ),
    ]
