# Generated by Django 3.0.6 on 2020-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200725_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='accountdefault.jpg', upload_to='member_pics/'),
        ),
    ]
